{% set name = "pytest-subtests" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ebd306a8dcf75133f1742f288c82f36426ebcf8a132d4ee89782d20e84fc13a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - pytest >=6.0
    - python >=3.6

test:
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture

extra:
  recipe-maintainers:
    - nicoddemus
