{% set name = "pytest-subtests" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51865c88457545f51fb72011942f0a3c6901ee9e24cbfb6d1b9dc1348bafbe37

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - pytest >=7.0
    - python >=3.6
    - attrs >=19.2.0

test:
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture

extra:
  recipe-maintainers:
    - nicoddemus
