{% set name = "pytest-subtests" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8849818a0a515e8052734888cd0f6701291fdbf77552664d9ac772a2f8cc8f0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - pytest >=7.4
    - python >={{ python_min }}
    - attrs >=19.2.0

test:
  requires:
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture

extra:
  recipe-maintainers:
    - nicoddemus
